package za.ac.cput.service.Impl;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import za.ac.cput.domain.Report;
import za.ac.cput.repository.ReportRepository;
import za.ac.cput.security.PdfGenerationUtility;
import za.ac.cput.service.IReportService;

import java.io.ByteArrayOutputStream;
import java.util.*;
import java.util.List;

@Service
public class ReportServiceImpl implements IReportService {

    private final ReportRepository reportRepository;
    private final PdfGenerationUtility pdfGenerationUtility;

    @Autowired
    public ReportServiceImpl(ReportRepository reportRepository, PdfGenerationUtility pdfGenerationUtility) {
        this.reportRepository = reportRepository;
        this.pdfGenerationUtility = pdfGenerationUtility;
    }

    @Override
    public Report create(Report report) {
        report = new Report.Builder()
                .copy(report)
                .setReportId(null)
                .setGeneratedAt(report.getGeneratedAt() != null ? report.getGeneratedAt() : java.time.LocalDate.now())
                .build();

        return reportRepository.save(report);
    }

    @Override
    public Report read(Integer integer) {
        return null;
    }


    @Override
    public byte[] generateReportPdf(Integer reportId) {
        // 1. Fetch the Report Entity
        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new NoSuchElementException("Report not found with ID: " + reportId));

        try {
            // The iTextDocument parameter is now correctly inferred as com.itextpdf.text.Document
            return pdfGenerationUtility.generatePdfBytes(iTextDocument -> { // <--- The type here is the issue
                // Define custom fonts for styling
                com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD, BaseColor.BLACK);
                com.itextpdf.text.Font contentFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12);

                // 3. Populate the PDF Document with Report Data

                // Title
                Paragraph title = new Paragraph("NURSING SYSTEM PLACEMENT REPORT", titleFont);
                title.setAlignment(Element.ALIGN_CENTER);
                iTextDocument.add(title); // FIX: This will work once the type is com.itextpdf.text.Document
                iTextDocument.add(Chunk.NEWLINE);

                // Report Details
                iTextDocument.add(new Paragraph("Report ID: " + report.getReportId(), contentFont));
                iTextDocument.add(new Paragraph("Report Name: " + report.getReportName(), contentFont));
                iTextDocument.add(new Paragraph("Date Generated: " + report.getGeneratedAt(), contentFont));
                iTextDocument.add(new Paragraph("Generated By: " + report.getGeneratedByUser(), contentFont));
                iTextDocument.add(Chunk.NEWLINE);
                iTextDocument.add(new Paragraph("----------------------------------", contentFont));

                // Report Content
                iTextDocument.add(new Paragraph("REPORT CONTENT:", titleFont));
                iTextDocument.add(Chunk.NEWLINE);
                iTextDocument.add(new Paragraph(report.getParametersJson(), contentFont));
            });

        } catch (NoSuchElementException e) {
            // Report not found (e.g., HTTP 404)
            throw e;
        } catch (DocumentException | java.io.IOException e) {
            // Handle PDF generation errors (e.g., Font issues, IO problems)
            System.err.println("Error generating PDF for Report ID " + reportId + ": " + e.getMessage());
            throw new RuntimeException("Failed to generate PDF report.", e);
        }
    }

    @Override
    public byte[] generatePlacementReport() {
        // This will hold the generated PDF content in memory
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        // 1. Create a Document instance
        Document document = new Document();

        try {
            // 2. Create a PdfWriter to link the document to the output stream
            PdfWriter.getInstance(document, baos);
            document.open();

            // ... proceed to Step 3 ...

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // 7. Ensure the document is closed
            document.close();
        }

        // 8. Return the raw PDF bytes
        return baos.toByteArray();
    }

    @Override
    public Report update(Report report) {
        if (report.getReportId() == null || !reportRepository.existsById(report.getReportId())) {
            throw new IllegalArgumentException("Report does not exist");
        }
        return reportRepository.save(report);
    }

    @Override
    public List<Report> findByReportName(String reportName) {
        return reportRepository.findByReportName(reportName);
    }

    @Override
    public List<Report> getAll() {
        return reportRepository.findAll();
    }

    @Override
    public void deleteById(Integer reportId) {
        if (reportRepository.existsById(reportId)) {
            reportRepository.deleteById(reportId);
        }
    }
}
